# Generated by Django 5.0.7 on 2024-10-14 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_studentlist'),
        ('facultyapp', '0002_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.studentlist'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.studentlist'),
        ),
    ]
