# Generated by Django 5.0.7 on 2024-10-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_studentlist'),
        ('facultyapp', '0004_studentlist_alter_addcourse_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentList',
        ),
    ]
